=== qb20nh/josa-complete/schemas/josa.config.model.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$ref": "#/definitions/JosaConfigSchema",
  "definitions": {
    "JosaConfigSchema": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "parenthesisToSkip": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "minLength": 2,
            "maxLength": 2,
            "uniqueItems": true
          },
          "description": "List of pair of parenthesis to skip when deciding the effective last letter of a word, formed as [\"opening\", \"closing\"]"
        },
        "punctuationsToIgnore": {
          "type": "string",
          "description": "List of characters to ignore when deciding the effective last letter of a word"
        },
        "alphabetWithPhoneticJongseong": {
          "$ref": "#/definitions/AlphabetWithPhoneticJongseong"
        },
        "josa": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/JosaElement"
          },
          "minLength": 1,
          "description": "Defines a unique josa appending case"
        }
      },
      "required": [
        "josa"
      ],
      "title": "JosaConfigObject",
      "description": "Controls some behavior of this package"
    },
    "AlphabetWithPhoneticJongseong": {
      "type": "object",
      "additionalProperties": {
        "type": "string",
        "maxLength": 1
      },
      "title": "AlphabetWithPhoneticJongseong",
      "description": "Maps an alphabet(or any character) to a phonetically equivalent hangul jongseong character"
    },
    "JosaElement": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "getterName": {
          "type": "string",
          "description": "Name of getter and appender function to use when generating code"
        },
        "whenTrue": {
          "type": "string",
          "description": "Josa string to use when branching function returned true"
        },
        "whenFalse": {
          "type": "string",
          "description": "Josa string to use when branching function returned false"
        },
        "usesCustomBranching": {
          "type": "boolean",
          "default": true,
          "description": "Whether if this josa completing case uses custom branching function, should define one manually in the code if set true"
        },
        "example": {
          "type": "object",
          "description": "Usage example for generating JSDoc",
          "properties": {
            "description": {
              "type": "string",
              "description": "Explanation of what it does"
            },
            "code": {
              "type": "string",
              "description": "Simple usage example code"
            }
          },
          "required": ["description", "code"],
          "additionalProperties": false
        }
      },
      "required": [
        "getterName",
        "whenFalse",
        "whenTrue"
      ],
      "title": "JosaElement"
    }
  }
}

=== qb20nh/josa-complete/src/josa.config.json
{
  "parenthesisToSkip": [
    ["(", ")"],
    ["[", "]"]
  ],
  "punctuationsToIgnore": ".?!\"”'’―…』》」〉",
  "alphabetWithPhoneticJongseong": {
    "L": "ㄹ",
    "M": "ㅁ",
    "N": "ㄴ",
    "R": "ㄹ"
  },
  "josa": [
    {
      "getterName": "은는",
      "whenTrue": "은",
      "whenFalse": "는",
      "example": {
        "description": "단어에 보조사 은/는 중 맞는 것을 붙여줍니다.",
        "code": "'산'.은는 === '산은'\n'바다'.은는 === '바다는'"
      }
    },
    {
      "getterName": "을를",
      "whenTrue": "을",
      "whenFalse": "를",
      "example": {
        "description": "단어에 대격조사 을/를 중 맞는 것을 붙여줍니다.",
        "code": "'산'.을를 === '산을'\n'바다'.을를 === '바다를'"
      }
    },
    {
      "getterName": "이가",
      "whenTrue": "이",
      "whenFalse": "가"
    },
    {
      "getterName": "와과",
      "whenTrue": "과",
      "whenFalse": "와"
    },
    {
      "getterName": "으로",
      "whenTrue": "으로",
      "whenFalse": "로",
      "usesCustomBranching": true
    },
    {
      "getterName": "야아",
      "whenTrue": "아",
      "whenFalse": "야"
    },
    {
      "getterName": "이여",
      "whenTrue": "이여",
      "whenFalse": "여"
    },
    {
      "getterName": "이나",
      "whenTrue": "이나",
      "whenFalse": "나"
    },
    {
      "getterName": "이다",
      "whenTrue": "이다",
      "whenFalse": "다"
    },
    {
      "getterName": "이였다",
      "whenTrue": "이었다",
      "whenFalse": "였다"
    },
    {
      "getterName": "이든",
      "whenTrue": "이든",
      "whenFalse": "든"
    },
    {
      "getterName": "이라",
      "whenTrue": "이라",
      "whenFalse": "라"
    },
    {
      "getterName": "이란",
      "whenTrue": "이란",
      "whenFalse": "란"
    },
    {
      "getterName": "이랑",
      "whenTrue": "이랑",
      "whenFalse": "랑"
    },
    {
      "getterName": "이야",
      "whenTrue": "이야",
      "whenFalse": "야"
    },
    {
      "getterName": "이며",
      "whenTrue": "이며",
      "whenFalse": "며"
    }
  ]
}
